### ISSUE TITLE
Unhandled stream error in pipe

### ISSUE THREAD

**Issue by mreinstein** [davidmarkclements/npm-dependents#3]
I'm running node@8.10.0 and see this for every module I try:

```bash
λ npm-dependents net-peer
net-peer has internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: Unexpected "h" at position 1 in state START
    at Parser.proto.charError (/usr/local/lib/node_modules/npm-dependents/node_modules/jsonparse/jsonparse.js:84:16)
    at Parser.proto.write (/usr/local/lib/node_modules/npm-dependents/node_modules/jsonparse/jsonparse.js:112:23)
    at Stream.<anonymous> (/usr/local/lib/node_modules/npm-dependents/node_modules/JSONStream/index.js:21:12)
    at Stream.stream.write (/usr/local/lib/node_modules/npm-dependents/node_modules/through/index.js:26:11)
    at write (/usr/local/lib/node_modules/npm-dependents/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/usr/local/lib/node_modules/npm-dependents/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/usr/local/lib/node_modules/npm-dependents/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:106:13)
    at DestroyableTransform.emit (events.js:208:7)
    at emitReadable_ (/usr/local/lib/node_modules/npm-dependents/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)

```

**Comment by davidmarkclements** [comment]
looks like it's expecting JSON and getting html 

it's likely the URL for querying the npm registry has changed, I wrote this in 2015

feel free to PR!
